services:
  configurator:
    environment:
      PROJECT_CLONE_URL: https://github.com/shelajev/labspace-demo-sbx-kits-dhi
      TERMINAL_URL: http://host.docker.internal:8085

  workspace: !override
    provider:
      type: labspace
      options:
        type: "ttyd"

  host-republisher: !reset null
