FROM node:24-trixie-slim

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY tsconfig.json ./
COPY src ./src
COPY public ./public

RUN npm run build \
  && npm cache clean --force

ENV NODE_ENV=production
EXPOSE 3000
CMD ["node", "dist/server.js"]
